<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Project_refer._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
 
    <form id="form1" runat="server">
 
  <!-- Content Wrapper. Contains page content -->


      <div class="row">
        <div class="col-md-12">
              <div class="box">
            <div class="box-header with-border" style="left: 0px; top: 2px">
              <h3 class="box-title">
                  
                 Project Referrals</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                                    <asp:GridView ID="GridViewReferral" runat="server" AllowPaging="True" AllowSorting="True" BackColor="White" HeaderStyle-CssClass="text-center" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="30px" CellPadding="10" Height="120px"  Width="1290px" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" HorizontalAlign="Center" DataKeyNames="ReferralID" DataSourceID="SqlDataSource1" >
                                        <AlternatingRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                        <Columns>
                                            <asp:BoundField DataField="ReferralID" HeaderText="ReferralID" InsertVisible="False" ReadOnly="True" SortExpression="ReferralID" />
                                            <asp:BoundField DataField="AdpNo" HeaderText="AdpNo" SortExpression="AdpNo" />
                                            <asp:BoundField DataField="ProjectCode" HeaderText="ProjectCode" SortExpression="ProjectCode" />
                                            <asp:BoundField DataField="Distric" HeaderText="Distric" SortExpression="Distric" />
                                            <asp:BoundField DataField="Apparent_Issue" HeaderText="Apparent_Issue" SortExpression="Apparent_Issue" />
                                            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                                            <asp:BoundField DataField="Desgination" HeaderText="Desgination" SortExpression="Desgination" />
                                            <asp:BoundField DataField="Contact" HeaderText="Contact" SortExpression="Contact" />
                                            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                                        </Columns>
                                        <FooterStyle BackColor="White" ForeColor="#000066" />
                                        <HeaderStyle BackColor="#C3D8F1" Font-Bold="True" ForeColor="#8B9FC8" Font-Size="15px" Height="40px"  HorizontalAlign="Center" VerticalAlign="Middle" Width="150px" />
                                        <PagerStyle BackColor="White" ForeColor="#000000" HorizontalAlign="Left" />
                                        <RowStyle ForeColor="#000066" Height="40px" HorizontalAlign="Center" VerticalAlign="Middle" />
                                        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                                        <SortedAscendingCellStyle BackColor="#F1F1F1" HorizontalAlign="Center" VerticalAlign="Middle" />
                                        <SortedAscendingHeaderStyle BackColor="#007DBB" HorizontalAlign="Center" VerticalAlign="Middle" />
                                        <SortedDescendingCellStyle BackColor="#CAC9C9" HorizontalAlign="Center" VerticalAlign="Middle" />
                                        <SortedDescendingHeaderStyle BackColor="#00547E" HorizontalAlign="Center" VerticalAlign="Middle" />
                                    </asp:GridView>
                                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [ReferralID], [AdpNo], [ProjectCode], [Distric], [Apparent_Issue], [Name], [Desgination], [Contact], [Email] FROM [tblReferral]"></asp:SqlDataSource>
         </div>
                  </div>
            
                <div class="box">
            <div class="box-header with-border" style="left: 0px; top: 2px">
              <h3 class="box-title">
                  
                  Monthly Recap Report</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-8">
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-8">
                  <div class="chart-responsive">
                    <canvas id="pieChart" height="150"></canvas>
                  </div>
                  <!-- ./chart-responsive -->
                </div>
                <!-- /.col -->
                <div class="col-md-4">
                  <ul class="chart-legend clearfix">
                    <li><i class="fa fa-circle-o text-red"></i> Chrome</li>
                    <li><i class="fa fa-circle-o text-green"></i> IE</li>
                    <li><i class="fa fa-circle-o text-yellow"></i> FireFox</li>
                    <li><i class="fa fa-circle-o text-aqua"></i> Safari</li>
                    <li><i class="fa fa-circle-o text-light-blue"></i> Opera</li>
                    <li><i class="fa fa-circle-o text-gray"></i> Navigator</li>
                  </ul>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
            </div>
   
          </div>
          <!-- /.box -->
                 
                  <!-- /.chart-responsive -->
                </div>
                <!-- /.col -->
               
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->


 




    </form>


 




</asp:Content>
